language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: f623246de128d55b91b81bd5b676bc7d825a3829
  keep-history: true
  on:
    branch: vuepress
