language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: 842cce78cd105985a2d9528d8ec0870bb9dc45d5
  keep-history: true
  on:
    branch: vuepress
