language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: 81ba37a3793dd8bcf1cb0ad04f6260b1bb92d533
  keep-history: true
  on:
    branch: vuepress
